import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/Components/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Mugs Intern",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link rel="icon" href="/public/images/next.svg" sizes="any" />
      <body className={inter.className}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
